### ISSUE TITLE
.ts extensions error

### ISSUE THREAD

**Issue by bessmorrell** [amiya-pattnaik/webdriverIO-with-mochaBDD#12]
Hello, I am new to webdriver, typescript, and json so I am having trouble fixing this error.

I get this error with the statement: 
import Page from './page.ts'
The error is: 
An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled. ts(5097)

My npm package versions:
├── @wdio/cli@8.3.8
├── bundler@0.8.0
├── ts-node@10.9.1
├── typescript@4.9.5
└── yarn@1.22.19

Should I include allowImportingExtensions in my json, or am I missing a different extension?

Thank you in advance.

**Comment by amiya-pattnaik** [comment]
It is difficult to recommend you unless we see what is in your node-module. I believe you are using your own package.josn rather than the package.json part of this boilerplate code. This is not an issue with  this boilerplate code. hence closing this.

pls try -
[add explicit .ts extensions to imports]
or 
remove the .ts extension when importing files.
